# Generated by Django 5.2 on 2025-05-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='manager',
        ),
    ]
